version: "3.7"

services:
  server:
    container_name: server
    restart: always
    build: api/
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - api/:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - api/data:/data/db
    ports:
      - "27017:27017"
  
  app:
    container_name: app
    restart: always
    build: app/
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - .:/usr/src/app
  